confirm_os_window_close 0
window_margin_width 5
font_family "JetBrains Mono"
bold_font auto
allow_remote_control socket-only
listen_on unix:${XDG_RUNTIME_DIR}/kitty-theme-switch-{kitty_pid}

include ../dotfiles-arch/themes/current/kitty.conf
