[global]
frame_color = "#31748f"
separator_color= frame
highlight = "#31748f"
corner_radius = 5
font = "JetBrains Mono 10"
icon_position = left

[urgency_low]
background = "#f7f7f7"
foreground = "#191724"

[urgency_normal]
background = "#f7f7f7"
foreground = "#191724"

[urgency_critical]
background = "#f7f7f7"
foreground = "#191724"
frame_color = "#eb6f92"
