layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi

layerrule = blur on, match:namespace waybar
layerrule = blur on, match:namespace gtk-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk-layer-shell
